# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5cbb07bca1885c7ddd24627635b03111"
name = "Draft Editor"
handle = "draft-editor"
application_url = "https://interact-motivated-districts-platform.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_draft_orders,write_draft_orders"

[auth]
redirect_urls = [
  "https://interact-motivated-districts-platform.trycloudflare.com/auth/callback",
  "https://interact-motivated-districts-platform.trycloudflare.com/auth/shopify/callback",
  "https://interact-motivated-districts-platform.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
